openapi: 3.0.3
info:
  title: STD23010 - TD3
  version: '1.0.2'
servers:
  - url: https://localhost.std23010.com
paths:
  /meal:
    get:
      parameters:
        - in: query
          name: page
          schema:
            type: integer
          required: true
        - in: query
          name: pageSize
          schema:
            type: integer
          required: true
      responses:
        200:
          description: meals'list
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Meal'
    post:
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                type: object
                properties:
                  name:
                    type: string
                  price:
                    type: double
        required: true
      responses:
        200:
          description: created meals'list
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Meal'
    put:
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Meal'
        required: true
      responses:
        200:
          description: updated meals'list
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Meal'
    delete:
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/MealIdentifier'
        required: true
      responses:
        200:
          description: deleted meals's
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Meal'
              
components:
  schemas:
    Meal:
      type: object
      properties:
        name:
          type: string
        price:
          type: number
          format: double
        id:
          type: string
    MealIdentifier:
      type: object
      properties:
        id:
          type: string
